version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mkisa23/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: mkisa23/kittygram_frontend:latest
    command: cp -r /app/build/. /app/static/
    volumes:
      - static:/app/static

  gateway:
    image: mkisa23/kittygram_gateway:latest
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html/static/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend
  